### ISSUE TITLE
Can we support BOTZ for higher versions of openfire?

### ISSUE THREAD

**Issue by krisiye** [igniterealtime/Botz#4]
Currently, it appears that BOTZ is not supported for open fire 4.8.x. Seems like a version compatibility issue with openfire modules and the xmpp server, method signatures etc. Possible to support this?

**Comment by guusdk** [comment]
I'm surprised at the timing of this request. Although it is definitely desired to have compatibility, there has not yet been an Openfire 4.8 release to date.

**Comment by krisiye** [comment]
Trying against openfire 4.7.4 - i am seeing the following:
```
java.lang.NullPointerException: Cannot invoke "org.jivesoftware.openfire.session.LocalClientSession.setAuthToken(org.jivesoftware.openfire.auth.AuthToken, String)" because "this.localClientSession" is null
	at org.igniterealtime.openfire.botz.BotzConnection.login(BotzConnection.java:375)
	at org.igniterealtime.openfire.botz.BotzConnection.login(BotzConnection.java:284)
```
It appears from reviewing the code that setAuthToken is supposed to create the client route and  the session. But seems to be failing right at `localClientSession = (LocalClientSession)SessionManager.getInstance().getSession(jid);`

Any pointers on what i maybe missing?

**Comment by guusdk** [comment]
I think you've uncovered one (of possibly many) bugs in the Botz framework. We've recreated this repository from sources that were very, very old, with next to no testing. Turns out that the Openfire API changed more than we anticipated.

I've provided a provisional fix for this issue in https://github.com/igniterealtime/Botz/pull/5 - care to give that a try?

**Comment by krisiye** [comment]
The fix was tested and works fine.  Able to create a session now and get the chatbot presence and exchange messages. Is there any good way with openfire to show this chatbot automatically under the users contact lists?

**Comment by guusdk** [comment]
Thanks for testing this @krisiye!

What you could do to add a chatbot to everyone's contact list is create a group in Openfire's admin console, and make the bot a member of that group. Then, you can Enable contact list group sharing, to make the group appear on the contact list of every user in the system.

![image](https://user-images.githubusercontent.com/4253898/223543686-e0de2299-6d0f-4fdc-8e24-81a0fb812ba4.png)

**Comment by krisiye** [comment]
@guusdk  -  it looks like the artifact may have some errors in the pipeline. Possible to get a 1.2 release with the updates? thanks!

**Comment by akrherz** [comment]
@krisiye I fixed up CI in #6 , so our maven repo should have an updated snapshot now.

**Comment by krisiye** [comment]
Thanks! When can we expect a release version?

**Comment by guusdk** [comment]
Given that #4 is pretty much preventing usage, I'm not seeing a reason to delay a new release. I've drafted one in https://github.com/igniterealtime/Botz/pull/7

**Comment by guusdk** [comment]
A release has been published: https://discourse.igniterealtime.org/t/botz-version-1-2-0-release/
